Created some models
mloncode/oss-llm-intellij pull request #10
Opened 2023-09-14 13:06 UTC by AragonerUA

2023-09-14 13:14 UTC, F47-503 requested changes
The main request is to move models to gpu before inference

2023-09-14 13:14 UTC, F47-503 commented on models/huggingface_models.py
> +    # tokenizer = LlamaTokenizer.from_pretrained("/output/path")
Better do not leave commented unused code like this

2023-09-14 13:14 UTC, F47-503 commented on models/huggingface_models.py
> +    output = model.generate(**tokenized)
Also move this model to GPU

2023-09-14 13:14 UTC, F47-503 commented on models/huggingface_models.py
> +    model = T5ForConditionalGeneration.from_pretrained('Salesforce/codet5-base')
All models must be on GPU if possible

2023-09-14 13:14 UTC, F47-503 commented on models/huggingface_models.py
> +    generated_ids = model.generate(input_ids, max_length=8)
Also better to use the same max_length default values for generation

2023-09-14 15:33 UTC, bzz commented on server/models/huggingface_models.py
> +        torch_dtype=torch.float16,
let's use `torch.bfloat16` but still that would be ~12Gb

I've used int4 quantisation

```
    nf4_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16
    )
    model_nf4 = AutoModelForCausalLM.from_pretrained(args.model, quantization_config=nf4_config)
    tokenizer = AutoTokenizer.from_pretrained(args.model)

    pipeline = transformers.pipeline(
        "text-generation",
        model=model_nf4,
        torch_dtype=torch.bfloat16,
        tokenizer=tokenizer
    )
```

2023-09-14 15:37 UTC, bzz commented on server/models/huggingface_models.py
> +    # starcoder_model("def print_hello_world():")
let's have a

```
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str, default="codellama/CodeLlama-7b-hf")
```

and a separate function to apply BitsAndBytesConfig for codelama.

Then the switch to starcoder will be by changing this CLI arg.

2023-09-15 10:00 UTC, bzz commented
ATM this can not be merged until the conflicts are resolved.

2023-09-17 09:58 UTC, bzz approved these changes
LGTM, thanks!

2023-09-27 07:54 UTC, merged